language: scala

sudo: false

addons:
  apt:
    packages:
      - oracle-java9-installer

before_install:
  - remove_dir_from_path $JAVA_HOME/bin
  - export JAVA_HOME=/usr/lib/jvm/java-9-oracle
  - export PATH=$JAVA_HOME/bin:$PATH
  - java -version

install:
  - mvn install dependency:go-offline -Pskip-formatter -DskipTests=true -q -f driver/pom.xml

script:
  - mvn install -P travis -B -f driver/pom.xml
  - cd tests-scala ; sbt test
